name: Build and Publish Commit

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

env:
  DOCKER_REGISTRY_USER: 2159f12a-43a7-448c-8149-b4538c3b5553
  DOCKER_REGISTRY_HOST: n11registry.azurecr.io
  DOCKER_REGISTRY_REPO: ecommerce-showcase/storefront

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v4
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      # setup Docker build action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY_HOST }}
          username: ${{ env.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          target: storefront
          tags: |
            ${{ env.DOCKER_REGISTRY_HOST }}/${{ env.DOCKER_REGISTRY_REPO }}:latest
          push: false

      - name: Docker push SHA tag to Azure
        uses: docker/build-push-action@v5
        with:
          # relative path to the place where source code with Dockerfile is located
          context: .
          target: storefront
          tags: |
            ${{ env.DOCKER_REGISTRY_HOST }}/${{ env.DOCKER_REGISTRY_REPO }}:${{ github.event.inputs.git-ref }}
          push: true
        if: ${{ github.event.inputs.git-ref != '' }}

